# Generated by Django 5.1.4 on 2026-06-08 16:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('OFFER', 'Offer'), ('REQUEST', 'Request')], max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('format', models.CharField(choices=[('ONLINE', 'Online'), ('PHYSICAL', 'Physical'), ('BOTH', 'Both')], default='ONLINE', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MATCHED', 'Matched'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mentorship_posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('compatibility_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('FINISHED', 'Finished')], default='PENDING', max_length=10)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_matches', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_matches', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_matches', to='mentoring.mentorshippost')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_matches', to='mentoring.mentorshippost')),
            ],
            options={
                'db_table': 'matches',
            },
        ),
        migrations.AddIndex(
            model_name='mentorshippost',
            index=models.Index(fields=['type', 'status'], name='mentorship__type_2b976d_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshippost',
            index=models.Index(fields=['subject'], name='mentorship__subject_4b0ea6_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshippost',
            index=models.Index(fields=['created_at'], name='mentorship__created_280abb_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshippost',
            index=models.Index(fields=['creator', 'status'], name='mentorship__creator_6feaca_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status'], name='matches_status_639056_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['mentor', 'status'], name='matches_mentor__fb198d_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['mentee', 'status'], name='matches_mentee__3d25ef_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['compatibility_score'], name='matches_compati_0bce3a_idx'),
        ),
    ]
