# Generated by Django 5.1.4 on 2026-06-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='verificationdocument',
            new_name='verificatio_status_a43286_idx',
            old_name='vd_status_idx',
        ),
        migrations.RenameIndex(
            model_name='verificationdocument',
            new_name='verificatio_user_id_d15fbf_idx',
            old_name='vd_user_status_idx',
        ),
    ]
